import { useState } from 'react'
import AuditCard from './AuditCard.jsx'
import { runAudit } from './auditApi.js'

const EXAMPLE_SPEC = `Feature: Personalized Engagement Nudges

We'll use ML to predict when users are about to close the app or reduce usage, and send them a push notification with personalized content to re-engage them. The system will run A/B tests to optimize the notification copy and timing for maximum click-through rate.

For premium users, we'll also send SMS nudges if push notifications go unread for 2+ hours. We'll track which users are most susceptible to re-engagement and create a "high-value engagement" segment to receive more frequent nudges (up to 12/day).

The notification content will be generated by analyzing the user's past behavior, friend activity, and browsing history. We'll use emotional language patterns that have historically driven the highest re-engagement rates. Users can opt out of notifications, but they'll need to navigate to Settings > Notifications > Personalization > Engagement to do so.`

const DIMENSIONS = [
  'user_harm',
  'misaligned_incentives',
  'dark_patterns',
  'privacy_risks',
  'fairness_concerns',
  'unintended_consequences',
]

const DIMENSION_LABELS = {
  user_harm: 'User Harm',
  misaligned_incentives: 'Misaligned Incentives',
  dark_patterns: 'Dark Patterns',
  privacy_risks: 'Privacy Risks',
  fairness_concerns: 'Fairness Concerns',
  unintended_consequences: 'Unintended Consequences',
}

function overallScoreStyle(score) {
  if (score <= 2) return { border: 'border-emerald-700', bg: 'bg-emerald-950/60', text: 'text-emerald-400', label: 'Low Risk', glow: 'shadow-emerald-900/40' }
  if (score <= 6) return { border: 'border-amber-700', bg: 'bg-amber-950/60', text: 'text-amber-400', label: 'Moderate Risk', glow: 'shadow-amber-900/40' }
  return { border: 'border-red-700', bg: 'bg-red-950/60', text: 'text-red-400', label: 'High Risk', glow: 'shadow-red-900/40' }
}

function buildMarkdownReport(spec, result) {
  const lines = [
    '# PM Alignment Audit Report',
    '',
    `**Overall Risk Score:** ${result.overall_risk_score}/10`,
    '',
    '## Executive Summary',
    '',
    result.executive_summary,
    '',
    '---',
    '',
  ]

  for (const dim of DIMENSIONS) {
    const d = result[dim]
    lines.push(`## ${DIMENSION_LABELS[dim]}`)
    lines.push('')
    lines.push(`**Score:** ${d.score}/10`)
    lines.push('')
    if (d.flagged_text?.length > 0) {
      lines.push('**Flagged:**')
      for (const f of d.flagged_text) lines.push(`- "${f}"`)
      lines.push('')
    }
    if (d.suggestions?.length > 0) {
      lines.push('**Recommendations:**')
      for (const s of d.suggestions) lines.push(`- ${s}`)
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push('## Audited Spec')
  lines.push('')
  lines.push('```')
  lines.push(spec)
  lines.push('```')

  return lines.join('\n')
}

function Spinner() {
  return (
    <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
    </svg>
  )
}

export default function App() {
  const [spec, setSpec] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const [copied, setCopied] = useState(false)

  async function handleAudit() {
    const text = spec.trim()
    if (!text) return
    setLoading(true)
    setError(null)
    setResult(null)
    try {
      const data = await runAudit(text)
      setResult(data)
    } catch (e) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  async function handleCopy() {
    if (!result) return
    const md = buildMarkdownReport(spec, result)
    await navigator.clipboard.writeText(md)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const style = result ? overallScoreStyle(result.overall_risk_score) : null

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans antialiased">
      {/* Top nav */}
      <header className="border-b border-slate-800 bg-slate-950/80 backdrop-blur sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center text-sm font-bold">A</div>
            <div>
              <h1 className="font-semibold text-slate-100 leading-none">PM Alignment Auditor</h1>
              <p className="text-xs text-slate-500 mt-0.5">Powered by Claude Sonnet</p>
            </div>
          </div>
          <span className="text-xs text-slate-600 hidden sm:block">Catch harms before they ship</span>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-10 flex flex-col gap-8">
        {/* Input section */}
        <section className="flex flex-col gap-4">
          <div>
            <h2 className="text-lg font-semibold text-slate-100">Product Spec or Feature Description</h2>
            <p className="text-sm text-slate-500 mt-1">
              Paste any spec, PRD excerpt, or feature description. Claude will analyze it across 6 safety and ethics dimensions.
            </p>
          </div>

          <textarea
            value={spec}
            onChange={e => setSpec(e.target.value)}
            placeholder={EXAMPLE_SPEC}
            rows={12}
            className="w-full rounded-xl border border-slate-700 bg-slate-900 text-slate-200 text-sm px-4 py-3 resize-y placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent leading-relaxed font-mono"
          />

          <div className="flex items-center gap-3">
            <button
              onClick={handleAudit}
              disabled={loading || !spec.trim()}
              className="flex items-center gap-2 px-6 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white text-sm font-semibold transition-colors duration-150 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-slate-950"
            >
              {loading ? <><Spinner /> Analyzing…</> : <>Run Audit</>}
            </button>

            {spec.trim() === '' && (
              <button
                onClick={() => setSpec(EXAMPLE_SPEC)}
                className="text-xs text-slate-500 hover:text-slate-300 transition-colors underline underline-offset-2"
              >
                Load example spec
              </button>
            )}
          </div>
        </section>

        {/* Error */}
        {error && (
          <div className="rounded-xl border border-red-800 bg-red-950/50 px-5 py-4 text-sm text-red-300">
            <strong className="font-semibold">Error:</strong> {error}
          </div>
        )}

        {/* Results */}
        {result && (
          <section className="flex flex-col gap-6">
            {/* Overall score banner */}
            <div className={`rounded-xl border ${style.border} ${style.bg} px-6 py-5 flex flex-col sm:flex-row sm:items-center gap-4 shadow-lg ${style.glow}`}>
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <span className={`text-4xl font-bold tabular-nums ${style.text}`}>{result.overall_risk_score}<span className="text-xl text-slate-500 font-normal">/10</span></span>
                  <span className={`text-sm font-semibold px-3 py-1 rounded-full border ${style.border} ${style.text} bg-slate-900/40`}>{style.label}</span>
                </div>
                <p className="text-sm text-slate-300 leading-relaxed max-w-2xl">{result.executive_summary}</p>
              </div>
              <button
                onClick={handleCopy}
                className="shrink-0 flex items-center gap-2 px-4 py-2 rounded-lg border border-slate-600 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-slate-500"
              >
                {copied ? (
                  <><span className="text-emerald-400">✓</span> Copied!</>
                ) : (
                  <><span>⎘</span> Copy Report</>
                )}
              </button>
            </div>

            {/* Dimension cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {DIMENSIONS.map(dim => (
                <AuditCard key={dim} dimension={dim} data={result[dim]} />
              ))}
            </div>

            <p className="text-xs text-slate-600 text-center pb-4">
              This audit is AI-generated and should complement, not replace, human judgment and expert review.
            </p>
          </section>
        )}
      </main>
    </div>
  )
}
